version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: cine_user
      POSTGRES_PASSWORD: cine_pass
      POSTGRES_DB: practica_sql_cine
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql